### PR TITLE
logging

### LINKED ISSUE #1: Logging
For fun and profit not really there's no money to be made

lets write a logger and here's some cool ideas that were dropped in the twitch chat by our very own and dear friend `grayhatter_`

```
//
// TODO - implement logging
//
//               6      5      4    3         2      1      0
// log levels: TRACE, DEBUG, INFO, NOTICE, WARNING, ERROR, NONE 
//
// logger::warning("some warniing text") or 
// logger::error("about to crash") 
// logging::warning("accepted connect from IPADDR")
//
// logger::warning() { if global <2; return null}
//
//
```

### PR DESCRIPTION
**Pull request by trvswgnr**
resolves #1

- added bespoke logging feature that works across multiple threads

currently uses `lazy_static`, but might be able to work around that since it seems like we want to keep things `std` only.

### CODE REVIEW

File: src/logger.rs [hunk 1]
```diff
@@ -0,0 +1,534 @@
...
+fn generate_temp_file_name() -> String {
+    let mut hasher = std::collections::hash_map::DefaultHasher::new();
+    let now = SystemTime::now();
+    let now_string = now.format("%Y-%m-%d %H:%M:%S%.3f %Z");
+    now_string.hash(&mut hasher);
+    let hash = hasher.finish();
+    let prefix = "temp-";
+    let suffix = ".log";
+    // make sure it's exactly 32 characters long
+    let len = 32 - prefix.len() - suffix.len();
```
Comment (twny) [inline src/logger.rs:104]: What happens if it's not 32 chars long?

**Review by twny — APPROVED** [review]

**Comment by twny** [comment]
i tried to merge this but i think i broke main by resolving conflicts the wrong way, then i couldn't get the project to build, finally did, and there were still several warnings... any ideas?
